#!/usr/bin/env python3
"""Walk data/raw/camargo/ and write results/inventory.md.

Lists the subjects and trials found, trials per mode and condition, NaN in the ankle
moment, stair heights and ramp inclines covered by each subject, and the sign of the
ankle moment and power in late stance (the push-off check of the sign convention).
Data: Camargo et al. (2021), J. Biomech. 119:110320, CC BY 4.0.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from anklesea import RAW_DIR, RESULTS_DIR, camargo
from anklesea.inventory import build_inventory

CITATION = (
    "Data: Camargo, Ramanathan, Flanagan, Young (2021), J. Biomech. 119:110320, "
    "doi:10.1016/j.jbiomech.2021.110320, CC BY 4.0."
)


def markdown_table(frame: pd.DataFrame) -> str:
    frame = frame.astype(object).where(frame.notna(), "")
    header = "| " + " | ".join(str(c) for c in frame.columns) + " |"
    rule = "|" + "|".join("---" for _ in frame.columns) + "|"
    rows = ["| " + " | ".join(str(v) for v in row) + " |" for row in frame.itertuples(index=False)]
    return "\n".join([header, rule, *rows])


def condition_label(row: pd.Series) -> str:
    if row["mode"] == "stair":
        return f"{row['stair_height_in']:g} in"
    if row["mode"] == "ramp":
        return f"{row['ramp_incline_deg']:g} deg"
    if row["mode"] == "levelground":
        return row["condition"]
    return "all speeds"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw", type=Path, default=RAW_DIR)
    parser.add_argument("--out", type=Path, default=RESULTS_DIR / "inventory.md")
    parser.add_argument("--subjects", nargs="+", default=None, help="subject IDs (default: all found)")
    args = parser.parse_args()

    inv = build_inventory(args.raw, subjects=args.subjects)
    if inv.empty:
        raise SystemExit(f"no complete trials under {args.raw}")
    inv["condition_label"] = inv.apply(condition_label, axis=1)
    subjects = sorted(inv["subject"].unique())
    lines = [
        "# Dataset inventory",
        "",
        f"Generated by `scripts/inventory.py` from the files in `data/raw/camargo/`. {CITATION}",
        "",
        f"Subjects with complete trials (`id`, `ik`, `gcRight` and `gcLeft` all present): {len(subjects)} "
        f"({', '.join(subjects)}). Trials: {len(inv)}. Samples at 200 Hz: {inv['n_samples'].sum():,}.",
        "",
        "## Trials per mode",
        "",
    ]
    per_mode = inv.pivot_table(index="subject", columns="mode", values="stem", aggfunc="count", fill_value=0)
    per_mode = per_mode.reindex(columns=[m for m in camargo.MODES if m in per_mode.columns]).reset_index()
    lines += [markdown_table(per_mode), ""]

    lines += ["## Trials per condition", "", "Stair heights and ramp inclines are read from the `conditions` files "
              "(`stairHeight` in inches) or, where absent, from the index in the trial name.", ""]
    for mode in ("levelground", "ramp", "stair"):
        sub = inv[inv["mode"] == mode]
        if sub.empty:
            continue
        table = sub.pivot_table(index="subject", columns="condition_label", values="stem", aggfunc="count", fill_value=0)
        if mode != "levelground":
            table = table[sorted(table.columns, key=lambda c: float(c.split()[0]))]
        lines += [f"**{mode}**", "", markdown_table(table.reset_index()), ""]

    tm = inv[inv["mode"] == "treadmill"]
    if not tm.empty:
        lines += ["**treadmill**: belt speed plateaus longer than 10 s found in each subject's trials (m/s).", ""]
        rows = []
        for subject, group in tm.groupby("subject"):
            speeds = sorted({s for tup in group["belt_speeds"] for s in tup})
            rows.append({"subject": subject, "plateaus": len(speeds), "min": min(speeds), "max": max(speeds)})
        lines += [markdown_table(pd.DataFrame(rows)), ""]

    missing_rows = []
    for mode, levels, unit in (("stair", camargo.STAIR_HEIGHT_IN, "in"), ("ramp", camargo.RAMP_INCLINE_DEG, "deg")):
        col = "stair_height_in" if mode == "stair" else "ramp_incline_deg"
        for subject in subjects:
            have = set(inv[(inv["subject"] == subject) & (inv["mode"] == mode)][col].dropna())
            missing = [f"{v:g} {unit}" for v in levels.values() if not any(abs(v - h) < 0.05 for h in have)]
            if missing:
                missing_rows.append({"subject": subject, "mode": mode, "missing": ", ".join(missing)})
    lines += ["## Missing stair heights and ramp inclines", ""]
    if missing_rows:
        lines += [markdown_table(pd.DataFrame(missing_rows)), ""]
    else:
        lines += ["None: every subject has every stair height and ramp incline.", ""]

    lines += ["## NaN in the ankle moment", "",
              "Counts of NaN samples in `ankle_angle_r_moment` and `ankle_angle_l_moment` (inverse dynamics). "
              "Runs are separate stretches of NaN in the right-leg moment.", ""]
    nan = inv.groupby("mode").agg(
        trials=("stem", "count"),
        samples=("n_samples", "sum"),
        nan_right=("moment_nan_r", "sum"),
        nan_left=("moment_nan_l", "sum"),
        trials_with_nan_right=("moment_nan_r", lambda s: int((s > 0).sum())),
        max_runs_right=("moment_nan_runs_r", "max"),
        nan_angle_right=("angle_nan_r", "sum"),
    )
    nan["nan_right_pct"] = (100 * nan["nan_right"] / nan["samples"]).round(2)
    nan["nan_left_pct"] = (100 * nan["nan_left"] / nan["samples"]).round(2)
    lines += [markdown_table(nan.reset_index()), ""]

    lines += [
        "## Sign convention check",
        "",
        "Mean right ankle moment, angular velocity and power over the samples at 45 to 60 % of the gait "
        "cycle (from `gcRight/HeelStrike`) that have a moment (the foot on a force plate), split by the "
        "steady locomotion label (treadmill: belt above 0.4 m/s). This is late stance, where the "
        "plantarflexors push off. With the OpenSim convention (dorsiflexion positive), push-off in "
        "walking, ramp ascent and stair ascent should show a negative (plantarflexion) moment, a "
        "negative (plantarflexing) velocity and a positive power. Ramp and stair descent are listed for "
        "comparison: there the ankle mostly absorbs energy.",
        "",
    ]
    rows = []
    for _, row in inv.iterrows():
        for label, (moment, velocity, power, n) in row["push_off"].items():
            rows.append({"activity": label, "moment": moment, "velocity": velocity, "power": power, "n": n})
    po = pd.DataFrame(rows)
    sign = po.groupby("activity").apply(
        lambda g: pd.Series(
            {
                "moment_Nm": np.average(g["moment"], weights=g["n"]),
                "velocity_rad_s": np.average(g["velocity"], weights=g["n"]),
                "power_W": np.average(g["power"], weights=g["n"]),
                "trials_with_negative_moment": f"{int((g['moment'] < 0).sum())}/{len(g)}",
            }
        ),
        include_groups=False,
    )
    sign[["moment_Nm", "velocity_rad_s", "power_W"]] = sign[["moment_Nm", "velocity_rad_s", "power_W"]].astype(float).round(2)
    lines += [markdown_table(sign.reset_index()), ""]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out} ({len(inv)} trials, {len(subjects)} subjects)")
    print(sign)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
